# Generated by Django 4.1.2 on 2022-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("phono_number", models.IntegerField()),
                ("password", models.CharField(max_length=10)),
                ("course_type", models.CharField(max_length=50)),
            ],
        ),
    ]
